import { HTTP_ERROR_HANDlER_PRIORITY } from '@malagu/core/lib/node';

export const ACCESS_DENIED_ERROR_HANDlER_PRIORITY = HTTP_ERROR_HANDlER_PRIORITY + 100;

export const AUTHENTICATION_ERROR_HANDlER_PRIORITY = ACCESS_DENIED_ERROR_HANDlER_PRIORITY + 100;
